### ISSUE TITLE
Adding RDFa+HTML and Microdata?

### ISSUE THREAD

**Issue by iherman** [dret/HTML5-overview#26] opened 2015-07-10 14:36 UTC
I do not know where you draw the line on what you consider part of the HTML5 world but, with the increasingly widespread usage of schema.org you may consider adding at least RDFa+HTML and Microdata (RDFa+HTML refers to the other RDFa documents but those are not to be added I believe).

If you prefer and agree, I can prepare a PR on this (at some point, not necessarily right now).

**Comment by dret** [comment] 2015-07-10 16:34
you probably have a point there. i started with all the API specs because that was the most active part specifically for HTML5, but RDFa also adds to the platform's capabilities. maybe adding RDFa then also implies to add the deceased microdata NOTE? what are your thoughts, @sideshowbarker?

**Comment by iherman** [comment] 2015-07-10 17:38
Personally, I think it was a mistake that Microdata is not published as a Rec, in view of its widespread usage, but that is not for me to say:-)

Incidentally, a similar question arises v.a.v. MathML and SVG. Those are (probably much more than RDFa and mdata) integral part of the HTML5 ecosystem, and they are not on the list either.

Again, I realize that a line has to be drawn somewhere…

Ivan

**Comment by dret** [comment] 2015-07-10 17:44
yes, drawing the line is a problem (and, like every such line, somewhat arbitrary and more a matter of choice than one of clear and indisputable facts). in the XML, you will find that some (incomplete) attempt was made to "classify" the specs, and that may become increasingly important. but then again, like every classification system, this in itself would be a big task and even more a matter of perspectives and choices, so i am hesitant to even get started again...
all that said, of course you're right that MathML and SVG matter for HTML; they just aren't quite along the line of the dozens of programmatic APIs that sprung up when HTML5 started, and that were the main motivation to start assembling information about that mix somewhere.

**Comment by dret** [comment] 2015-09-16 17:34
created a separate issue for MathML #28

**Comment by dret** [comment] 2015-09-16 21:49
@iherman, is https://github.com/dret/HTML5-overview/commit/e5f3fb5744d6f61d5dd29e840729efa26e254814 looking good enough regarding MathML, or do you think other specs should be added as well? thanks!

**Comment by dret** [comment] 2015-09-16 21:55
adding SVG now is on the to-do list as well: #29

**Comment by sideshowbarker** [comment] 2015-09-16 23:00
IMHO and FWIW for the record here, I don’t think it’s appropriate to include either RDFa or Microdata in this particular overview, because they are both outside of the scope of what I believe the overview’s scope is (or should be).

Specifically: I take the scope of this overview to be limited to **features that are actually implemented  in the Web runtime itself** (or targeted to be implemented in the Web runtime itself)—and so that **features that Web developers can used and rely on to be interoperable across all UAs that conformingly implement a Web runtime**.

By that criteria, it’s not that RDFa and Microdata aren’t features that Web developers can expect interoperability for among implementations of a Web runtime—it’s instead that they are not features that require any kind of support in the Web runtime itself and so are completely orthogonal to the scope of this overview.

So omitting RDFa and Microdata would not degrade the accuracy of the overview at all. But including them risks misleading Web developers into assuming that there is some kind of native support required for them in the Web runtime in order to use them properly. Which there clearly is not.

**Comment by sideshowbarker** [comment] 2015-09-16 23:13
Addendum: I continue to find it exasperating that basically ever single time we try to come up with some list of technologies like this, this is the way it ends up evolving:

1. The list starts out being very useful, and relatively tightly scoped and with a sane, clearly defined set of criteria about what ought to be included.
2. At some point, we start piling other particular pet/hobbyhorse technologies of our own into it that don’t actually fit—doing that I guess, out of fear (or something) that if we don’t, people won’t regard those technologies as important or relevant.
3. Repeat step 2 until the list degrades into being essentially useless in practice with regard to being a solution to the original problem it was intended to address, and it just becomes one more list to be ignored.

I personally would like for this overview in this repo to continue to be accurate and useful and to not get scope-creeped into irrelevance like other lists we’ve done in the past have become. Because I think it its current form (at least what its current form was before the RDFa and Microdata specs were added) it is a  useful list that can point other people to with confidence.

But my confidence about it is eroded each time things get added like RDFa and Microdata that don’t rightly belong in this particular list.

**Comment by dret** [comment] 2015-09-17 03:27
just to be clear, @sideshowbarker: RDFa and Microdata currently are not included because I share your concerns about scope creep. and your feedback so far has been very much appreciated (and also has mostly been integrated, i think). so keep it coming, and if you have any ideas on how to improve things, please let me know!

**Comment by sideshowbarker** [comment] 2015-09-17 04:29
> just to be clear, @sideshowbarker: RDFa and Microdata currently are not included because I share your concerns about scope creep

d'oh! OK, sorry for overreacting on that.

> your feedback so far has been very much appreciated (and also has mostly been integrated, i think). so keep it coming, and if you have any ideas on how to improve things, please let me know!

Thanks—I remain very glad to have this overview, and have been pointing quite a few people to it (including people on the W3C team, as far is it being the right way to go about making a resource like this). So thanks for making and it and for improving it and always being receptive to feedback.

**Comment by dret** [comment] 2015-10-16 22:50
thanks. as usual, any feedback is greatly appreciated.on this particular issue, i happen to agree with @sideshowbarker that this should be about the actual platform, and not the (potentially very large) set of technologies that may be associated with it in some shape or form. i am closing this for now.

**Closed by dret** 2015-10-16 22:50 UTC
