### ISSUE TITLE
add ARIA in HTML

### ISSUE THREAD

**Issue by stevefaulkner** [dret/HTML5-overview#18] opened 2015-06-10 14:31 UTC
http://www.w3.org/TR/html-aria/
This specification defines the web developer rules (author conformance requirements) for the use of [wai-aria-1.1] attributes on [HTML51] elements. It also defines requirements for Conformance Checking tools.

**Comment by dret** [comment] 2015-06-10 15:07
maybe this is a duplicate of #12?

**Comment by sideshowbarker** [comment] 2015-06-12 02:42
> maybe this is a duplicate of #12?

http://www.w3.org/TR/html-aria/ is a separate spec from the ARIA spec; it's a [Rec-track chartered deliverable of its own](http://www.w3.org/2013/09/html-charter.html#deliverables) in the HTML WG and defines normative document-conformance requirements for ARIA in HTML specifically—whereas the ARIA spec itself defines general language-neutral requirements for all “host languages” that might incorporate ARIA attributes into their specs.

So IHMO the ARIA in HTML spec should definitely be included in the **Working Drafts** of this overview.

**Comment by dret** [comment] 2015-07-07 19:10
is https://github.com/dret/HTML5-overview/commit/9ca181076da431aa08e203d56f427476832d7380 sufficient to make everybody happy? if so, please close issue. thx!

**Comment by dret** [comment] 2016-04-23 17:38
assuming the fix was good enough, closing this issue.

**Closed by dret** 2016-04-23 17:38 UTC
